### ISSUE TITLE
Clarify license situation

### ISSUE THREAD

**Issue by grigorig** [DieTechniker/kks-encryption#1]
The project does not have any license information, nor are there any license headers in the source files. Is this project supposed to be Open Source? As is, the code should be considered proprietary and cannot be safely used by anyone.

Please attach an Open Source license to the project or clarify the licensing otherwise.

**Comment by JanThiel** [comment]
Hi @grigorig, all our projects here are free and open source in the very way it's ment to be.
So thank your very much for pointing out the missing license. We will have this fixed asap.

Best regards,

Jan

**Comment by loetifuss** [comment]
@grigorig @JanThiel added Apache License 2.0
