### ISSUE TITLE
(Non-)usage of parameter "employerNumber" in "sign" and "decrypt"

### ISSUE THREAD

**Issue by marcusfey** [DieTechniker/kks-encryption#3]
In `PKCS7EncryptionServiceImpl` in methods `sign` and `decrypt` the respective parameters `employerNumber` are never used (for the latter only as part of an exception message). Instead `PKCS7KeyLocator` is called without any arguments.

Thus changing the values used in the provided JUnit test methods (i.e. a different values inside both `signAndEncrypt` and `decryptAndVerify`) also yields constant success.

Is this intended?

**Comment by JanThiel** [comment]
Hi @marcusfey Thank you for noticing. We will have this checked.

**Comment by loetifuss** [comment]
@marcusfey correct, for signing and decryption no parameter is needed since we only need the private key (which is static). Exception handling could probably be changed to avoid the extra parameter.

**Comment by loetifuss** [comment]
The library has been significantly redesigned and improved (thx to @christian-schlichtherle). With the latest version the parameter is removed from sign and decrypt methods.
