### ISSUE TITLE
Doesn't compile on Java 8

### ISSUE THREAD

**Issue by loetifuss** [DieTechniker/kks-encryption#6]
Currently the build fails to compile on Java 8 for two main reasons:

1.
`options.release.set(8)` only works on Java > 8 and will throw: invalid flag: --release
Proposed workaround: use `sourceCompatibility = "1.8"` and `targetCompatibility = "1.8"`

2.
compileJava fails in DirContextVisitor
`src\main\java\de\tk\security\kks\DirContextVisitor.java:40: error: incompatible types: cannot infer type-variable(s) T
                                .from(attr::getAll)
                                     ^
    (argument mismatch; invalid method reference
      getAll() in Attribute is defined in an inaccessible class or interface)
  where T is a type-variable:
    T extends Object declared in method <T>from(Callable<NamingEnumeration<T>>)
1 error`

tested with JDK 1.8.0_221

**Comment by christian-schlichtherle** [comment]
That's intentional. For building the JARs, a JDK >= 9 is required. At runtime, only a JRE >= 1.8 is required. You can download ready-made JARs and distributions from here: https://github.com/DieTechniker/kks-encryption/actions

**Comment by christian-schlichtherle** [comment]
The workaround doesn't figure the use of Java API > 1.8, that's why the `options.release.set(8)` is preferable.

**Comment by loetifuss** [comment]
If source level needs to be Java >= 9 it's fair enough if it works for Java 8 at runtime

**Comment by christian-schlichtherle** [comment]
No worries, source _and_ target level are indeed set to 1.8. The build just needs a JDK >= 9 to set the "--release 1.8" switch, which ensures that the boot classpath matches 1.8, too. Otherwise, you could run the build with the latest JDK and use it's JRE API, which is to be avoided.
