### ISSUE TITLE
fat-jar misses generators for apsec private key

### ISSUE THREAD

**Issue by marcusfey** [DieTechniker/kks-encryption#9]
Encryption using the current fat-jar fails for private P12 files generated by apsec, key generator 2.16.840.1.101.3.4.1.42 is missing ([missing 2.16.840.1.101.3.4.1.42.txt](https://github.com/DieTechniker/kks-encryption/files/5156295/missing.2.16.840.1.101.3.4.1.42.txt)). It works if I add BC jars manually to the classpath (before kks-encryption). 

Example file: [999911114.p12.zip](https://github.com/DieTechniker/kks-encryption/files/5156315/999911114.p12.zip)

Also it seems a several other algorithms are missing:
- [list-BC.txt](https://github.com/DieTechniker/kks-encryption/files/5156292/list-BC.txt)
- [list-fat-jar.txt](https://github.com/DieTechniker/kks-encryption/files/5156294/list-fat-jar.txt)

Is this intented/to be expected?

**Comment by christian-schlichtherle** [comment]
The fat-jar has been minimized. If an algorithm is only referenced by a string (OID) or via reflection, then the minimizer may disregard it. Do you have an example for reproduction of the issue?

**Comment by marcusfey** [comment]
The ZIP contains the private key (sorry, forgot to include the password). 

I used this class to test it [KksTest.java.txt](https://github.com/DieTechniker/kks-encryption/files/5157436/KksTest.java.txt). The LDAP address is intentionally screwed up to verify that the aforementioned issue occurs before LDAP access (i.e. it should be reproducible).

**Comment by christian-schlichtherle** [comment]
The fat JAR is indeed missing necessary classes. I have opened another pull request which removes the shrinking/minimizing step so that the fat JAR now contains all the classes from Bouncy Castle - at the expense of more than doubling its size.

On another note: Your code sample will not work without the LDAP service because you have configured no other directory.

If you just want to test your key store you can simply use the main class of the fat JAR:

```bash
$ java -jar kks-*-all.jar -recipient 999911114 -source message.in -sink message.cms -keystore 999911114.p12 -storepass diga -alias 999911114
$ java -jar kks-*-all.jar -source message.cms -sink message.out -keystore 999911114.p12 -storepass diga -alias 999911114
$ cmp message.{in,out}
```

(after downloading the new fat JAR, of course)

**Comment by marcusfey** [comment]
Thanks for fixing and the remark! 

I'll have a look. We do need LDAP access indeed for outside subscribers. Talking to yourself was the easiest way to get started ;-)
